HOST = 'localhost'
CLIENT_PORT = 10003
SERVER_PORT_WORKERS = 10001
SERVER_PORT_CLIENTS = 11000

MAX_WORKERS = 10 #max workers to assign
MAX_TSDIFF = 10 #max ts difference to declare a worker not availabale

CHECK_JOBS_SLEEP = 1
CHECK_WORKERS_SLEEP = 1
PING_SLEEP = 1

NEW_WORKERS = 0
DEAD_WORKERS = 1
